[server]
port = 50051

[auth]
internal_token = "internal_token"
jwt_secret = "jwt_secret"
github_client_id = "github_client_id"
github_client_secret = "github_client_secret"
github_redirect_url = "http://localhost:8080/auth/callback"
oauth_state_expiration = "10m"
token_expiration = "24h"

[redis]
urls = "localhost:6379"

[gorm_client.database]
driver = "sqlite"
name = "data/users.db"
sslmode = "disable"
